### ISSUE TITLE
Class functions are not supported

### ISSUE THREAD

**Issue by benruijl** [romis2012/aiohttp-basicauth#1]
I cannot put the decorator around class functions that take `self` as an argument:

```python
    @auth.required
    async def main(self, request):
        return web.Response(text='Private view')
```

```log
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/lib/python3.7/site-packages/aiohttp_basicauth/__init__.py", line 67, in __call__
    return await handler(request)
TypeError: wrapper() takes 1 positional argument but 2 were given
```

**Comment by romis2012** [comment]
Fixed in version 0.1.3
